### ISSUE TITLE
ADR - Radar and HUD

### ISSUE THREAD

**Issue by thoraxe** [redhat-gamedev/srt-multiplayer-game-design#6]
# ADR Context / Overview
A player needs some details about the status of their ship and where they are in the game universe.

Additionally, there are many situations where a player will not be able to see any other player ships on their screen. Some kind of "radar" system is necessary to provide details on the nearest/closest other players.

## Decision 
<Describe here our response to these forces, that is, the design decision that was made. State the decision in full sentences, with active voice ("We will...").>

## Rationale 
<Describe here the rationale for the design decision. Also indicate the rationale for significant *rejected* alternatives. This section may also indicate assumptions, constraints, requirements, and results of evaluations and experiments.>

## Status
<[Proposed | Accepted | Deprecated | Superseded]
If deprecated, indicate why. If superseded, include a link to the new ADR. >

## Consequences
<Describe here the resulting context, after applying the decision. All consequences should be listed, not just the "positive" ones. >

## Authors
< _at_ anyone involved in the decision >

**Comment by thoraxe** [comment]
# Proposal
## HUD
* Show my current HP
* Show my current speed
* Show my current sector
* Show my missile status (as currently you can only fire one missile at a time and it's possible that missile would be off-screen)

### Considerations
* Where do we want this information displayed?
* What details do we show about other players on screen?

## Radar
The ~[Elite Dangerous](https://i.imgur.com/qbCzUAT.png) radar provides an interesting reference. We are not dealing with 3D space, but perhaps we can still implement something similar. However, as a less ambitious MVP, we could simply have a 180-degree circle with dots that show whether anything is in the forward-looking arc of the direction that the ship is pointed. Maybe the "weight" of the dot could indicate the closeness of the object. 

### Considerations
* How far away should the radar be able to see?
* What happens when there are a ton of other players near-ish?

**Comment by dudash** [comment]
Adding inline of your linked image:
![image](https://user-images.githubusercontent.com/116840/176204910-c59cddf5-f8b2-420a-8213-3c5c9f16a564.png)

Note that this is a logarithmic scale radar allowing us to fit objects even farther away than we could if it was linear.

**Comment by dudash** [comment]
Some other considerations to have around radar is for longer range weapons. One inspiration for me is The Expanse. I'm thinking of the types of ships and the weapons they carried. perimeter defense guns (PDCs), rail guns, missiles/torpedos... PDCs being close range on screen... but maybe longer range could leverage the torpedos and radars info. If we did that long range, we'd need to have some way for defense of incoming offscreen torpedo attacks - or I think gameplay would be frustrating.

**Comment by dudash** [comment]
For the MVP 180 degree circle idea - we could put a [small hex grid inside](https://i.imgur.com/AJoDm.gif) (7 or 19) showing near range adjacent tiles - and then the outer ring (circle) showing more distant objects directionally only.

**Comment by RoddieKieley** [comment]
HUD potentially inspired by the
[Wing Commander Flat Universe](https://media.indiedb.com/images/members/3/2359/2358515/profile/cap20150729221122.jpg) HUD.

**Comment by Raygun4K** [comment]
Here is what I have so far for the hud design. @thoraxe @RoddieKieley @dudash
![2022_SRT_Hud__1 0](https://user-images.githubusercontent.com/24488428/176948602-1196429b-4bd4-4eaf-a969-d0da12ed0959.png)

**Comment by thoraxe** [comment]
@Raygun4K i like where it's going. it's definitely a good start. I think we decided against showing the sector -- it's not useful. Then you could move the speed to the bottom-left and we can probably ship it (pun intended).

**Comment by Raygun4K** [comment]
@thoraxe Please see attached. Thanks
![2022_SRT_Hudv2](https://user-images.githubusercontent.com/24488428/177340754-e81ce09a-955f-440b-9053-7ee775633e50.png)
!

**Comment by Raygun4K** [comment]
@thoraxe Here you go
![2022_SRT_Hudv2](https://user-images.githubusercontent.com/24488428/177341258-2aa8e2bd-3174-4850-b71d-efed0f2b277f.png)
!

**Comment by thoraxe** [comment]
Closed by quite a few different PRs in the client.
