### ISSUE TITLE
ADR - Client space missile animation

### ISSUE THREAD

**Issue by thoraxe** [redhat-gamedev/srt-multiplayer-game-design#7]
# ADR Context / Overview
The space missiles should look awesome. They should also do cool explode-y things when they hit a ship. They should fizzle out in some interesting way when their timer runs out.

## Decision 
* When a missile is created/appears, there should be an interesting animation.
* As the missile travels, it should be animated.
* When the missile collides with another object, there should be a neat explosion.

## Rationale 
The missiles should be visually interesting. This will make the game more engaging.

## Status
**Accepted**

## Consequences
None known at this time.

## Authors
@thoraxe 
@dudash 
@RoddieKieley 
Kaliq Ray
Luke Dary

**Comment by thoraxe** [comment]
The primary consideration right now is that the server should be (it may not be) sending a "missile remove" message. However:

* When a missile is created/appears, there should be an interesting animation.
* As the missile travels, it should be animated.
* When the missile collides with another object, there should be a neat explosion.
* When the missile is removed/expires, there should be an interesting animation.

**Comment by thoraxe** [comment]
Missile creation/removal messages are complete. (see https://github.com/redhat-gamedev/srt-godot-server/pull/22)

**Comment by blfetche** [comment]
@thoraxe I can help with this.

**Comment by thoraxe** [comment]
@blfetche https://github.com/redhat-gamedev/srt-godot-client/issues/3

Would you like me to assign this one to you? If you can do this, it will free up Kaliq to do the HUD/Radar designs.

**Comment by Raygun4K** [comment]
@thoraxe  I just finished doing the missile launch muzzle flash, the missile travel burn, missile explosion, and the missile expire animation. I used blender to export image sequences. Where do we have the hud inspiration stored? I can't find it.

**Comment by thoraxe** [comment]
Since the missile timeout information is not sent in the messages at this time, it was removed from the design. We will need to open a new ADR to reintroduce "natural" missile expiration animations if we decide to add those details to the server messaging.

**Comment by blfetche** [comment]
> @blfetche [redhat-gamedev/srt-godot-client#3](https://github.com/redhat-gamedev/srt-godot-client/issues/3)
> 
> Would you like me to assign this one to you? If you can do this, it will free up Kaliq to do the HUD/Radar designs.

@thoraxe Sure I can take this on if it is still an option to work on. Thanks. Sorry for the delayed response I was on vacation and was catching up to this week.
